# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202602030705
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from secure_access.models.alert import Alert
from secure_access.models.list_alerts200_response import ListAlerts200Response
from secure_access.models.test_email_notification_response import TestEmailNotificationResponse
from secure_access.models.test_notification import TestNotification
from secure_access.models.time_range import TimeRange
from secure_access.models.update_alerts_status200_response import UpdateAlertsStatus200Response
from secure_access.models.update_alerts_status_request import UpdateAlertsStatusRequest

from secure_access.api_client import ApiClient, RequestSerialized
from secure_access.api_response import ApiResponse
from secure_access.rest import RESTResponseType


class AlertsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_alert_by_id(
        self,
        alert_id: Annotated[StrictStr, Field(description="The unique identifier of the alert.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Alert:
        """Get Alert

        Get the details for the specific alert sent by the system to the organization.

        :param alert_id: The unique identifier of the alert. (required)
        :type alert_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_alert_by_id_serialize(
            alert_id=alert_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Alert",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_alert_by_id_with_http_info(
        self,
        alert_id: Annotated[StrictStr, Field(description="The unique identifier of the alert.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Alert]:
        """Get Alert

        Get the details for the specific alert sent by the system to the organization.

        :param alert_id: The unique identifier of the alert. (required)
        :type alert_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_alert_by_id_serialize(
            alert_id=alert_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Alert",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_alert_by_id_without_preload_content(
        self,
        alert_id: Annotated[StrictStr, Field(description="The unique identifier of the alert.")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Alert

        Get the details for the specific alert sent by the system to the organization.

        :param alert_id: The unique identifier of the alert. (required)
        :type alert_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_alert_by_id_serialize(
            alert_id=alert_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Alert",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_alert_by_id_serialize(
        self,
        alert_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if alert_id is not None:
            _path_params['alertId'] = alert_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/admin/v2/alerting/alerts/{alertId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_alerts(
        self,
        status: Annotated[Optional[StrictInt], Field(description="Filter by the status of the alert. - 1 (Active) - 2 (Dismissed) - 3 (Resolved) - 4 (Archived)")] = None,
        severity: Annotated[Optional[StrictInt], Field(description="Filter for the alerts by severity (1=High, 2=Medium, 3=Low ,4=Info).")] = None,
        last_created_at: Annotated[Optional[datetime], Field(description="Filter for the alerts in the collection that the system created on the specified timestamp.")] = None,
        modified_at: Annotated[Optional[datetime], Field(description="Filter for the alerts in the collection that the system modified on the specified timestamp.")] = None,
        alert_name: Annotated[Optional[StrictStr], Field(description="Filter for the alerts in the collection by the alert name.")] = None,
        pattern_search: Annotated[Optional[StrictStr], Field(description="Provide a search pattern to query for by the alert name, rule name, or rule category name.")] = None,
        only_active_alerts_count: Annotated[Optional[StrictBool], Field(description="Query for the count of the active alerts only.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of items to return from the collection in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The default offset is 0.")] = None,
        time_range: Annotated[Optional[TimeRange], Field(description="Filter for the alerts in the collection that occur in the time range. Provide a start_time and end_time using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `time_range` query parameter with the `created_after` filter.")] = None,
        created_after: Annotated[Optional[datetime], Field(description="Filter for the alerts in the collection that the system created after the timestamp. Provide a date and time (ISO 8601) using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `created_after` query parameter with the `time_range` filter.")] = None,
        include_context: Annotated[Optional[StrictBool], Field(description="Include the context field in each alert response. The context contains additional metadata about the alert.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListAlerts200Response:
        """List Alerts

        Get the properties of the alerts for the organization.

        :param status: Filter by the status of the alert. - 1 (Active) - 2 (Dismissed) - 3 (Resolved) - 4 (Archived)
        :type status: int
        :param severity: Filter for the alerts by severity (1=High, 2=Medium, 3=Low ,4=Info).
        :type severity: int
        :param last_created_at: Filter for the alerts in the collection that the system created on the specified timestamp.
        :type last_created_at: datetime
        :param modified_at: Filter for the alerts in the collection that the system modified on the specified timestamp.
        :type modified_at: datetime
        :param alert_name: Filter for the alerts in the collection by the alert name.
        :type alert_name: str
        :param pattern_search: Provide a search pattern to query for by the alert name, rule name, or rule category name.
        :type pattern_search: str
        :param only_active_alerts_count: Query for the count of the active alerts only.
        :type only_active_alerts_count: bool
        :param limit: The maximum number of items to return from the collection in the response.
        :type limit: int
        :param offset: The place to start reading in the collection. The default offset is 0.
        :type offset: int
        :param time_range: Filter for the alerts in the collection that occur in the time range. Provide a start_time and end_time using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `time_range` query parameter with the `created_after` filter.
        :type time_range: TimeRange
        :param created_after: Filter for the alerts in the collection that the system created after the timestamp. Provide a date and time (ISO 8601) using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `created_after` query parameter with the `time_range` filter.
        :type created_after: datetime
        :param include_context: Include the context field in each alert response. The context contains additional metadata about the alert.
        :type include_context: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_alerts_serialize(
            status=status,
            severity=severity,
            last_created_at=last_created_at,
            modified_at=modified_at,
            alert_name=alert_name,
            pattern_search=pattern_search,
            only_active_alerts_count=only_active_alerts_count,
            limit=limit,
            offset=offset,
            time_range=time_range,
            created_after=created_after,
            include_context=include_context,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListAlerts200Response",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_alerts_with_http_info(
        self,
        status: Annotated[Optional[StrictInt], Field(description="Filter by the status of the alert. - 1 (Active) - 2 (Dismissed) - 3 (Resolved) - 4 (Archived)")] = None,
        severity: Annotated[Optional[StrictInt], Field(description="Filter for the alerts by severity (1=High, 2=Medium, 3=Low ,4=Info).")] = None,
        last_created_at: Annotated[Optional[datetime], Field(description="Filter for the alerts in the collection that the system created on the specified timestamp.")] = None,
        modified_at: Annotated[Optional[datetime], Field(description="Filter for the alerts in the collection that the system modified on the specified timestamp.")] = None,
        alert_name: Annotated[Optional[StrictStr], Field(description="Filter for the alerts in the collection by the alert name.")] = None,
        pattern_search: Annotated[Optional[StrictStr], Field(description="Provide a search pattern to query for by the alert name, rule name, or rule category name.")] = None,
        only_active_alerts_count: Annotated[Optional[StrictBool], Field(description="Query for the count of the active alerts only.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of items to return from the collection in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The default offset is 0.")] = None,
        time_range: Annotated[Optional[TimeRange], Field(description="Filter for the alerts in the collection that occur in the time range. Provide a start_time and end_time using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `time_range` query parameter with the `created_after` filter.")] = None,
        created_after: Annotated[Optional[datetime], Field(description="Filter for the alerts in the collection that the system created after the timestamp. Provide a date and time (ISO 8601) using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `created_after` query parameter with the `time_range` filter.")] = None,
        include_context: Annotated[Optional[StrictBool], Field(description="Include the context field in each alert response. The context contains additional metadata about the alert.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListAlerts200Response]:
        """List Alerts

        Get the properties of the alerts for the organization.

        :param status: Filter by the status of the alert. - 1 (Active) - 2 (Dismissed) - 3 (Resolved) - 4 (Archived)
        :type status: int
        :param severity: Filter for the alerts by severity (1=High, 2=Medium, 3=Low ,4=Info).
        :type severity: int
        :param last_created_at: Filter for the alerts in the collection that the system created on the specified timestamp.
        :type last_created_at: datetime
        :param modified_at: Filter for the alerts in the collection that the system modified on the specified timestamp.
        :type modified_at: datetime
        :param alert_name: Filter for the alerts in the collection by the alert name.
        :type alert_name: str
        :param pattern_search: Provide a search pattern to query for by the alert name, rule name, or rule category name.
        :type pattern_search: str
        :param only_active_alerts_count: Query for the count of the active alerts only.
        :type only_active_alerts_count: bool
        :param limit: The maximum number of items to return from the collection in the response.
        :type limit: int
        :param offset: The place to start reading in the collection. The default offset is 0.
        :type offset: int
        :param time_range: Filter for the alerts in the collection that occur in the time range. Provide a start_time and end_time using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `time_range` query parameter with the `created_after` filter.
        :type time_range: TimeRange
        :param created_after: Filter for the alerts in the collection that the system created after the timestamp. Provide a date and time (ISO 8601) using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `created_after` query parameter with the `time_range` filter.
        :type created_after: datetime
        :param include_context: Include the context field in each alert response. The context contains additional metadata about the alert.
        :type include_context: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_alerts_serialize(
            status=status,
            severity=severity,
            last_created_at=last_created_at,
            modified_at=modified_at,
            alert_name=alert_name,
            pattern_search=pattern_search,
            only_active_alerts_count=only_active_alerts_count,
            limit=limit,
            offset=offset,
            time_range=time_range,
            created_after=created_after,
            include_context=include_context,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListAlerts200Response",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_alerts_without_preload_content(
        self,
        status: Annotated[Optional[StrictInt], Field(description="Filter by the status of the alert. - 1 (Active) - 2 (Dismissed) - 3 (Resolved) - 4 (Archived)")] = None,
        severity: Annotated[Optional[StrictInt], Field(description="Filter for the alerts by severity (1=High, 2=Medium, 3=Low ,4=Info).")] = None,
        last_created_at: Annotated[Optional[datetime], Field(description="Filter for the alerts in the collection that the system created on the specified timestamp.")] = None,
        modified_at: Annotated[Optional[datetime], Field(description="Filter for the alerts in the collection that the system modified on the specified timestamp.")] = None,
        alert_name: Annotated[Optional[StrictStr], Field(description="Filter for the alerts in the collection by the alert name.")] = None,
        pattern_search: Annotated[Optional[StrictStr], Field(description="Provide a search pattern to query for by the alert name, rule name, or rule category name.")] = None,
        only_active_alerts_count: Annotated[Optional[StrictBool], Field(description="Query for the count of the active alerts only.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of items to return from the collection in the response.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The default offset is 0.")] = None,
        time_range: Annotated[Optional[TimeRange], Field(description="Filter for the alerts in the collection that occur in the time range. Provide a start_time and end_time using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `time_range` query parameter with the `created_after` filter.")] = None,
        created_after: Annotated[Optional[datetime], Field(description="Filter for the alerts in the collection that the system created after the timestamp. Provide a date and time (ISO 8601) using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `created_after` query parameter with the `time_range` filter.")] = None,
        include_context: Annotated[Optional[StrictBool], Field(description="Include the context field in each alert response. The context contains additional metadata about the alert.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Alerts

        Get the properties of the alerts for the organization.

        :param status: Filter by the status of the alert. - 1 (Active) - 2 (Dismissed) - 3 (Resolved) - 4 (Archived)
        :type status: int
        :param severity: Filter for the alerts by severity (1=High, 2=Medium, 3=Low ,4=Info).
        :type severity: int
        :param last_created_at: Filter for the alerts in the collection that the system created on the specified timestamp.
        :type last_created_at: datetime
        :param modified_at: Filter for the alerts in the collection that the system modified on the specified timestamp.
        :type modified_at: datetime
        :param alert_name: Filter for the alerts in the collection by the alert name.
        :type alert_name: str
        :param pattern_search: Provide a search pattern to query for by the alert name, rule name, or rule category name.
        :type pattern_search: str
        :param only_active_alerts_count: Query for the count of the active alerts only.
        :type only_active_alerts_count: bool
        :param limit: The maximum number of items to return from the collection in the response.
        :type limit: int
        :param offset: The place to start reading in the collection. The default offset is 0.
        :type offset: int
        :param time_range: Filter for the alerts in the collection that occur in the time range. Provide a start_time and end_time using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `time_range` query parameter with the `created_after` filter.
        :type time_range: TimeRange
        :param created_after: Filter for the alerts in the collection that the system created after the timestamp. Provide a date and time (ISO 8601) using the YYYY-MM-DD HH:MM:SS format. **Note:** You cannot use the `created_after` query parameter with the `time_range` filter.
        :type created_after: datetime
        :param include_context: Include the context field in each alert response. The context contains additional metadata about the alert.
        :type include_context: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_alerts_serialize(
            status=status,
            severity=severity,
            last_created_at=last_created_at,
            modified_at=modified_at,
            alert_name=alert_name,
            pattern_search=pattern_search,
            only_active_alerts_count=only_active_alerts_count,
            limit=limit,
            offset=offset,
            time_range=time_range,
            created_after=created_after,
            include_context=include_context,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListAlerts200Response",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_alerts_serialize(
        self,
        status,
        severity,
        last_created_at,
        modified_at,
        alert_name,
        pattern_search,
        only_active_alerts_count,
        limit,
        offset,
        time_range,
        created_after,
        include_context,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if status is not None:
            
            _query_params.append(('status', status))
            
        if severity is not None:
            
            _query_params.append(('severity', severity))
            
        if last_created_at is not None:
            if isinstance(last_created_at, datetime):
                _query_params.append(
                    (
                        'last_created_at',
                        last_created_at.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('last_created_at', last_created_at))
            
        if modified_at is not None:
            if isinstance(modified_at, datetime):
                _query_params.append(
                    (
                        'modified_at',
                        modified_at.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('modified_at', modified_at))
            
        if alert_name is not None:
            
            _query_params.append(('alert_name', alert_name))
            
        if pattern_search is not None:
            
            _query_params.append(('pattern_search', pattern_search))
            
        if only_active_alerts_count is not None:
            
            _query_params.append(('only_active_alerts_count', only_active_alerts_count))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if time_range is not None:
            
            _query_params.append(('time_range', time_range))
            
        if created_after is not None:
            if isinstance(created_after, datetime):
                _query_params.append(
                    (
                        'created_after',
                        created_after.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('created_after', created_after))
            
        if include_context is not None:
            
            _query_params.append(('include_context', include_context))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/admin/v2/alerting/alerts',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def send_alert_notifications(
        self,
        test_notification: TestNotification,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> TestEmailNotificationResponse:
        """Create Test Alert by Email

        Create a test notification and send the alert to the recipients configured in the alert rule.

        :param test_notification: (required)
        :type test_notification: TestNotification
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_alert_notifications_serialize(
            test_notification=test_notification,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TestEmailNotificationResponse",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def send_alert_notifications_with_http_info(
        self,
        test_notification: TestNotification,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[TestEmailNotificationResponse]:
        """Create Test Alert by Email

        Create a test notification and send the alert to the recipients configured in the alert rule.

        :param test_notification: (required)
        :type test_notification: TestNotification
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_alert_notifications_serialize(
            test_notification=test_notification,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TestEmailNotificationResponse",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def send_alert_notifications_without_preload_content(
        self,
        test_notification: TestNotification,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Create Test Alert by Email

        Create a test notification and send the alert to the recipients configured in the alert rule.

        :param test_notification: (required)
        :type test_notification: TestNotification
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_alert_notifications_serialize(
            test_notification=test_notification,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "TestEmailNotificationResponse",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _send_alert_notifications_serialize(
        self,
        test_notification,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if test_notification is not None:
            _body_params = test_notification


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/admin/v2/alerting/alerts/testNotifications/Email',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def update_alerts_status(
        self,
        update_alerts_status_request: UpdateAlertsStatusRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> UpdateAlertsStatus200Response:
        """Update Status of Alerts

        Update the status of the alerts in the organization.

        :param update_alerts_status_request: (required)
        :type update_alerts_status_request: UpdateAlertsStatusRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_alerts_status_serialize(
            update_alerts_status_request=update_alerts_status_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "UpdateAlertsStatus200Response",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '422': "Model422Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def update_alerts_status_with_http_info(
        self,
        update_alerts_status_request: UpdateAlertsStatusRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[UpdateAlertsStatus200Response]:
        """Update Status of Alerts

        Update the status of the alerts in the organization.

        :param update_alerts_status_request: (required)
        :type update_alerts_status_request: UpdateAlertsStatusRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_alerts_status_serialize(
            update_alerts_status_request=update_alerts_status_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "UpdateAlertsStatus200Response",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '422': "Model422Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def update_alerts_status_without_preload_content(
        self,
        update_alerts_status_request: UpdateAlertsStatusRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update Status of Alerts

        Update the status of the alerts in the organization.

        :param update_alerts_status_request: (required)
        :type update_alerts_status_request: UpdateAlertsStatusRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_alerts_status_serialize(
            update_alerts_status_request=update_alerts_status_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "UpdateAlertsStatus200Response",
            '400': "Alerting400Error",
            '401': "Alerting401Error",
            '403': "Alerting403Error",
            '404': "Alerting404Error",
            '422': "Model422Error",
            '429': "Model429Error",
            '500': "Alerting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _update_alerts_status_serialize(
        self,
        update_alerts_status_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if update_alerts_status_request is not None:
            _body_params = update_alerts_status_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='PUT',
            resource_path='/admin/v2/alerting/alerts/status',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


